nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['http://localhost:4321']
        allow_credentials: true
        allow_headers: ['Content-Type', 'Authorization', 'Accept']
        expose_headers: ['Content-Disposition', 'Link']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        max_age: 3600
    paths:
        '^/api/':
            allow_origin: ['http://localhost:4321']
            allow_credentials: true
            allow_headers: ['Content-Type', 'Authorization', 'Accept']
            expose_headers: ['Content-Disposition', 'Link']
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
            max_age: 3600