# config/packages/reset_password.yaml
symfonycasts_reset_password:
    # Le decimos qué clase usaremos para almacenar y leer los tokens
    request_password_repository: App\Repository\ResetPasswordRequestRepository
    # Tiempo de vida de cada token en segundos
    lifetime: 3600
